### ISSUE TITLE
真帅，把默认dom节点加到配置里面如何

### ISSUE THREAD

**Issue by minliacom** [halo-sigs/plugin-lightgallery#2]
像最后一行那样，这样就有一个默认配置了，不用每次去点开设置

```
apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-lightgallery-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          help: 填写扫描图片的区域的 DOM 节点，支持 CSS 选择器，如：#content
          label: DOM 节点选择
          name: dom_selector
          validation: required
          value: "#content"
```
