### ISSUE TITLE
建议灯箱背景为半透明样式

### ISSUE THREAD

**Issue by jocksliu** [halo-sigs/plugin-lightgallery#24]
可能是个人喜好，不过参考类似语雀、飞书文档等平台，灯箱样式看到大部分都是半透明背景凸显高亮的中间图片，我当前在halo2.18.0版本中安装的lightgallery 1.2.1，看到灯箱背景是纯黑色的，并在找了设置，没有看到相关的调整项，于是自己在halo系统设置里代码注入覆盖了纯黑的背景，整体效果如下，感觉朦胧背景比纯黑背景相对好看些，建议作者添加或者开发设置项
![image](https://github.com/user-attachments/assets/ea6a37bc-8676-4412-98bf-232ae125b8a9)

**Comment by jocksliu** [comment]
注入代码如下：
```css
<style>
.lg-backdrop {
    background-color: rgba(128, 128, 128, 0.9) !important;
}
.lg-close.lg-icon {
    color: #fff !important;
}
.lg-next, .lg-prev {
    color: #fff !important;
}
.lg-outer .lg-thumb-outer {
    background-color: rgba(100, 100, 100, 0.9) !important;
}
.lg-sub-html {
    color: #fff !important;
}
</style>
```
